name: baker
on: push
jobs:
    bakersjob:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
            - uses: appleboy/ssh-action@v1.2.5
              with:
                host: ${{secrets.REMOTE_HOST}}
                username: ${{ secrets.REMOTE_USER }}
                key: ${{ secrets.SSH_PRIVATE_KEY }}
                port: 22
                script: |
                    cd ~/homebaker-backend
                    git pull origin main
                    npm install --production
                    pm2 restart bakerlane || pm2 start app.js --name "bakerlane"

